markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: achaospace
author: "Achao"
email: kxxmsy@gmail.com
name: "Achao个人博客"
url: https://achaospace.github.io
domain: https://achaospace.github.io
all_categories: [
["webfront", "web前端开发","/posts/webfront.html"], 
["webback", "web后端开发","/posts/webback.html"],
["web", "Web建站","/posts/web.html"], 
["demo", "demo展示","/posts/demo.html"],
# ["read", "读书笔记","/posts/read.html"], 
# ["other", "杂记","/posts/other.html"],
# ["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
